version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  yoga:
    image: dmitrypetukhov/yoga-backend:latest
    restart: always
    volumes:
      - static_value_yoga:/app/Yoga/static/
      - media_value_yoga:/app/Yoga/media/
    depends_on:
      - db

  plan:
    image: dmitrypetukhov/plan:v1
    restart: always
    volumes:
      - static_value_plan:/app/Plan/static/
      - media_value:/app/Plan/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - yoga
      - plan
    restart: always

volumes:
  static_value:
  media_value:
  static_value_plan:
  static_value_yoga:
  media_value_yoga: 
  db_value:
