# Generated by Django 2.2.19 on 2023-01-14 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20230114_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donemaidate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planmaidate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serial',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='train',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train', to=settings.AUTH_USER_MODEL),
        ),
    ]
