server {
    listen 80;
    server_tokens off;
    server_name 194.187.122.3;
    client_max_body_size 32m;

    location /static/ {
        root /var/html/;
    }

    location /media/ {
        root /var/html/;
    }

    location / {
        proxy_pass http://plan:8000;
    }
}