# Generated by Django 2.2.16 on 2023-07-16 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField(max_length=100, verbose_name='Тип СИ')),
                ('dunumber', models.TextField(max_length=100, verbose_name='Номер DU')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('location', models.CharField(choices=[('ЕКБ', 'Екатеринбург'), ('ЧЛБ', 'Челябинск'), ('Пермь', 'Пермь'), ('МСК', 'Москва'), ('СПБ', 'Санкт-Петербург'), ('Сочи', 'Сочи'), ('Крюково', 'Крюково'), ('КЛГ', 'Калининград')], default='ЕКБ', max_length=30, verbose_name='Локация')),
                ('model', models.TextField(max_length=100, verbose_name='Модель СИ')),
                ('maker', models.TextField(max_length=100, verbose_name='Производитель')),
                ('number', models.TextField(max_length=100, verbose_name='Номер в госреестре')),
                ('control_type', models.CharField(choices=[('Калибровка', 'Калибровка'), ('Поверка', 'Поверка')], default='Поверка', max_length=30, verbose_name='Тип метрологического контроля')),
                ('periodicity', models.IntegerField(verbose_name='Периодичность проверки, мес.')),
                ('seral_number', models.TextField(max_length=100, verbose_name='Серийный номер')),
                ('date_control', models.DateField(verbose_name='Дата проверки')),
                ('date_end', models.DateField(verbose_name='Дата окончания поверки')),
                ('place', models.TextField(max_length=100, verbose_name='Фактическое местоположение')),
                ('in_act', models.BooleanField(default=False, verbose_name='Наличие в акте РЖД')),
                ('note', models.TextField(max_length=100, verbose_name='Примечание')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='metrolog/', verbose_name='Руководство')),
                ('default', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual', to=settings.AUTH_USER_MODEL)),
                ('metrolog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='metrolog.Measurement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='metrolog/', verbose_name='Сертификат')),
                ('default', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to=settings.AUTH_USER_MODEL)),
                ('metrolog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='metrolog.Measurement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['created'], name='metrolog_me_created_d7cd78_idx'),
        ),
        migrations.AddIndex(
            model_name='manual',
            index=models.Index(fields=['created'], name='metrolog_ma_created_5de614_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['created'], name='metrolog_ce_created_c29223_idx'),
        ),
    ]
