# Generated by Django 2.2.16 on 2023-07-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='dunumber',
            field=models.CharField(max_length=100, verbose_name='Номер DU'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='maker',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель СИ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='note',
            field=models.CharField(max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер в госреестре'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Фактическое местоположение'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='seral_number',
            field=models.CharField(max_length=100, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип СИ'),
        ),
    ]
