# Generated by Django 2.2.16 on 2023-07-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0003_auto_20230717_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cases/', verbose_name='Фотография СИ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='metrolog/', verbose_name='Новый сертификат'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название сертификата'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date_control',
            field=models.DateField(verbose_name='Дата выдачи сертификата'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания действия сертификата'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация, проводящая метрологический контроль'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='organization_fact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация, фактически проводившая метрологический контроль'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='periodicity',
            field=models.IntegerField(verbose_name='Периодичность метрологического контроля, мес.'),
        ),
    ]
