# Generated by Django 2.2.16 on 2023-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0004_auto_20230720_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Фотография СИ'),
        ),
    ]
