# Generated by Django 2.2.16 on 2023-07-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0005_auto_20230720_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия сертификата'),
        ),
    ]
