# Generated by Django 2.2.16 on 2023-07-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0006_auto_20230721_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='days',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Осталось дней'),
        ),
    ]
