# Generated by Django 2.2.16 on 2023-07-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0007_measurement_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='metrolog/', verbose_name='Фотография СИ'),
        ),
    ]
