# Generated by Django 2.2.16 on 2023-09-08 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0008_auto_20230721_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificateauthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Актуальность сертификата'),
        ),
    ]
