# Generated by Django 2.2.16 on 2025-11-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrolog', '0010_auto_20250509_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='location',
            field=models.CharField(choices=[('ЕКБ', 'Екатеринбург'), ('ЧЛБ', 'Челябинск'), ('Пермь', 'Пермь'), ('МСК', 'Москва'), ('СПБ', 'Санкт-Петербург'), ('Сочи', 'Сочи'), ('Крюково', 'Крюково'), ('КЛГ', 'Калининград'), ('НН', 'Нижний Новгород'), ('Самара', 'Самара')], default='ЕКБ', max_length=30, verbose_name='Локация'),
        ),
    ]
