# Generated by Django 2.2.19 on 2023-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='day_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Среднесуточный пробег'),
        ),
        migrations.AlterField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Plan/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='train',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег на дату'),
        ),
        migrations.AlterField(
            model_name='train',
            name='mileage_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата считывания пробега'),
        ),
        migrations.AlterField(
            model_name='train',
            name='renter',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Арендатор'),
        ),
    ]
