# Generated by Django 2.2.16 on 2023-02-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donemaidate',
            options={'ordering': ['maintenance_date']},
        ),
    ]
