# Generated by Django 2.2.16 on 2025-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donemaidate',
            name='place',
            field=models.CharField(choices=[('ЕКБ', 'Екатеринбург'), ('ЧЛБ', 'Челябинск'), ('Пермь', 'Пермь'), ('МСК', 'Москва'), ('СПБ', 'Санкт-Петербург'), ('Сочи', 'Сочи'), ('Крюково', 'Крюково'), ('КЛГ', 'Калининград'), ('НН', 'Нижний Новгород')], default='ЕКБ', max_length=30, verbose_name='Место проведения'),
        ),
    ]
