# Generated by Django 2.2.16 on 2023-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20230125_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donemaidate',
            name='place',
            field=models.CharField(choices=[('ЕКБ', 'Екатеринбург'), ('ЧЛБ', 'Челябинск'), ('Пермь', 'Пермь'), ('МСК', 'Москва'), ('СПБ', 'Санкт-Петербург'), ('Сочи', 'Сочи'), ('Крюково', 'Крюково')], default='ЕКБ', max_length=30, verbose_name='Место проведения'),
        ),
    ]
