# Generated by Django 2.2.19 on 2023-01-14 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20230113_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
