# Generated by Django 2.2.16 on 2023-01-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20230125_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donemaidate',
            options={'ordering': ['maintenance_date']},
        ),
    ]
