# Generated by Django 2.2.16 on 2023-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_auto_20230126_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('Vi', 'Vi'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('I4+I5', 'I4+I5'), ('I5', 'I5'), ('I6', 'I6'), ('30', '30 суток'), ('Зима', 'Зима'), ('Лето', 'Лето'), ('-', '-'), ('Vi*', 'Vi*'), ('I1*', 'I1*'), ('I2*', 'I2*')], default='Vi', max_length=5, verbose_name='Тип инспекции'),
        ),
    ]
