# Generated by Django 2.2.16 on 2023-02-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_auto_20230204_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donemaidate',
            options={'ordering': ['mileage']},
        ),
    ]
