# Generated by Django 2.2.16 on 2023-01-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_auto_20230126_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donemaidate',
            options={'ordering': ['created']},
        ),
    ]
