# Generated by Django 2.2.16 on 2023-02-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_auto_20230204_1743'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donemaidate',
            name='train_maintenance_rel',
        ),
    ]
