# Generated by Django 2.2.16 on 2023-02-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_auto_20230204_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='donemaidate',
            name='delete',
            field=models.BooleanField(default=True),
        ),
    ]
