# Generated by Django 2.2.16 on 2023-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_auto_20230126_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='order',
            field=models.BooleanField(default=True, verbose_name='Плановый инспекции по порядку'),
        ),
    ]
