# Generated by Django 2.2.16 on 2023-02-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_donemaidate_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donemaidate',
            old_name='delete',
            new_name='musthave',
        ),
    ]
