# Generated by Django 2.2.16 on 2023-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_auto_20230215_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='file',
            field=models.FileField(null=True, upload_to='<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
