# Generated by Django 2.2.16 on 2023-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_auto_20230301_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='file',
            field=models.FileField(null=True, upload_to='cases/', verbose_name='Прикрепленный документ'),
        ),
    ]
