# Generated by Django 2.2.16 on 2023-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_auto_20230304_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cases/', verbose_name='Прикрепленный документ'),
        ),
    ]
