# Generated by Django 2.2.16 on 2023-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_auto_20230304_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cases/', verbose_name='Прикрепленный документ'),
        ),
    ]
