# Generated by Django 2.2.16 on 2023-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_auto_20230312_1745'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donemaidate',
            name='train_maintenance_date',
        ),
        migrations.AddConstraint(
            model_name='donemaidate',
            constraint=models.UniqueConstraint(fields=('train', 'maintenance_date', 'maintenance'), name='train_maintenance_date'),
        ),
    ]
